"""Core package for loan monitoring services."""

from .config import (  # noqa: F401
    Config,
    Thresholds,
    Terms,
    ObservabilitySettings,
    KnowledgeQuestion,
    HedgingSettings,
    WebSettings,
    load_config,
    resolve_config_path,
    resolve_secrets_path,
)
from .db import get_connection  # noqa: F401
from .logging_setup import setup_logging  # noqa: F401
from .metrics import get_metrics, init_metrics_server  # noqa: F401
from .security import AuthManager, SecuritySettings, SecurityUser  # noqa: F401
from .services import (  # noqa: F401
    PriceService,
    LoanState,
    LTVMonitor,
    ReserveManager,
    ExchangeManager,
    RepaymentService,
    plan_collateral,
    simulate_volatility,
    stress_test,
    VolatilityPoint,
    compute_ltv,
    price_drop_to_reach_ltv,
    DashboardSnapshot,
    gather_dashboard_snapshot,
    render_dashboard,
    ReportingService,
    LTVHistoryEntry,
    HedgingService,
    HedgingConsentError,
    HedgingDisabledError,
    HedgeQuote,
    PayoffPoint,
)
from .secrets import SecretManager  # noqa: F401
from .web import create_app as create_web_app, app as web_app  # noqa: F401

__all__ = [
    "Config",
    "Thresholds",
    "Terms",
    "ObservabilitySettings",
    "KnowledgeQuestion",
    "HedgingSettings",
    "WebSettings",
    "load_config",
    "resolve_config_path",
    "resolve_secrets_path",
    "get_connection",
    "setup_logging",
    "get_metrics",
    "init_metrics_server",
    "AuthManager",
    "SecuritySettings",
    "SecurityUser",
    "PriceService",
    "LoanState",
    "compute_ltv",
    "price_drop_to_reach_ltv",
    "LTVMonitor",
    "ReserveManager",
    "ExchangeManager",
    "RepaymentService",
    "plan_collateral",
    "simulate_volatility",
    "stress_test",
    "VolatilityPoint",
    "DashboardSnapshot",
    "gather_dashboard_snapshot",
    "render_dashboard",
    "ReportingService",
    "LTVHistoryEntry",
    "HedgingService",
    "HedgingConsentError",
    "HedgingDisabledError",
    "HedgeQuote",
    "PayoffPoint",
    "SecretManager",
    "create_web_app",
    "web_app",
]
